name: github-trending

on:
  schedule:
  - cron: "00 4 * * *"
  workflow_dispatch:

jobs:
  github-trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: yarn install
        run: npm install --global typescript yarn && yarn && yarn build
        working-directory: .
      - name: fetch data
        run: node src/actions/github-trending.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_BASE_URL: ${{ secrets.AI_BASE_URL }}
