name: Telegram Notification
on:
  issues:
    types: [opened]
jobs:
  send-to-telegram:
    runs-on: ubuntu-latest
    if: github.event.issue.author_association == 'OWNER'
    steps:
    - name: Send message to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: 'markdown'
        message: ${{ github.event.issue.body }}
    - name: Close Issues
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const issueNumber = ${{ github.event.issue.number }};
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              state: "closed"
            });
